// tag::resume[]
// tag::position[]
= Poste - *Consultant* - 2007/2011

// end::position[]
// tag::company[]
== Gemalto, Montréal

Produit SIMMessenger. Développement d'une passerelle pour la messagerie instantanée sur mobile à l'aide de SMS

Services financiers mobile.

// end::company[]
// end::resume[]
// tag::achivements[]
* [Strong verb] + [job duty] + [impact]
* Analyze IT infrastructure needs to determine project scope and resources
* Designed and implemented new cloud architecture solutions for clients, reducing customer churn by 30%
* Translate technical specifications for systems into product requirements and internal documents
* Work with developers to streamline the development process and reduce production time

* Architecture, conception et développement Java des applications serveur
* Développement de clients Smartphones
* Applications de services financiers mobiles
* Application de messagerie instantanée

* Participer à la mise en place d'un cadre hautement sécurisé pour les services financiers mobiles (banque, porte-monnaie électronique, etc.).
* Travail sur le développement du backend Serveur
* Travail sur le développement d'applications clientes Android, iOS et Blackberry (Version 7 et antérieures).
* Développement réalisé en Agile Scrum

// end::achivements[]
// tag::environment[]
Environnement::
* Java
* Framework OSGI
* Eclipse
* JAXB
* XML
* XSLT

// end::environment[]
