// tag::resume[]
// tag::position[]
= Architecte Logiciels - Consultant - Août 2021/Juillet 2022

// end::position[]
// tag::company[]
== Banque Nationale, Montréal

Services numériques aux entreprises (BNE)

Conception d'une architecture logicielle pour synchroniser l'ancien MS SQL Server avec MDM-AE en utilisant les micro-services dans AWS EKS.

Gestion d'un repo GitHub pour centraliser les fichiers OpenAPI afin de forcer le développement des contrats avant le code.

// end::company[]
// end::resume[]
// tag::achivements[]
* [Strong verb] + [job duty] + [impact]
* Analyze IT infrastructure needs to determine project scope and resources
* Designed and implemented new cloud architecture solutions for clients, reducing customer churn by 30%
* Translate technical specifications for systems into product requirements and internal documents
* Work with developers to streamline the development process and reduce production time

// end::achivements[]
// tag::environment[]
Environnement::
* Environnement SAFe (équipe applicative de plus de 100 collaborateurs)
* AWS
* EKS
* SQS
* Kubernetes
* Kafka
* Docker
* Java 11
* Spring webflux

// end::environment[]




