# https://resumeworded.com/solutions-architect-resume-examples
# https://www.indeed.com/career-advice/resumes-cover-letters/solution-architect-resume

// tag::resume[]
// tag::position[]
= Septembre 2025/Décembre 2025 BNC - Architecte Solution (Consultant)

Responsable de concevoir, documenter et superviser la mise en œuvre des solutions technologiques répondant aux besoins d’affaires. Pont entre les équipes métier, les développeurs et les opérations, en s’assurant que les solutions sont alignées avec les standards d’architecture, les exigences de sécurité et les objectifs stratégiques de l’entreprise.

// end::position[]
// tag::company[]
== Banque nationale du Canada
* Montréal, Canada
* 29 000 employé.e.s
* Services financiers

// end::company[]
// end::resume[]

// tag::achivements[]
// tag::project[]
=== Banque numérique
* [Strong verb] + [job duty] + [impact]
* Analyze IT infrastructure needs to determine project scope and resources
* Designed and implemented new cloud architecture solutions for clients, reducing customer churn by 30%
* Translate technical specifications for systems into product requirements and internal documents
* Work with developers to streamline the development process and reduce production time

// end::project[]
// end::achivements[]

// tag::environment[]
Environnement::
* AWS
* Golang
* Confluence
* Jira
* EventCatalog

// end::environment[]
