// tag::resume[]
// tag::position[]
= November 2011/December 2020 Morgan Stanley - Senior Java Developer (Permanent)

Enterprise Application Development, Delivery Manager and Solutions Architect – US Institutional Tax Withholding.

// end::position[]
// tag::company[]
== Morgan Stanley
* Montreal. Canada
* 60,000 employees
* Investment banking and asset management.

// end::company[]
// end::resume[]

// tag::achievements[]
// tag::project[]
=== 871m

Developer, project manager and solutions architect designing and implementing a new transaction capture and cash flow aggregation system for equity derivatives.

* Using Taxman 3 architecture
* Creation of application documentation
* Unit testing implemented using JUnits and Mockito

// end::project[]
// tag::project[]
=== Taxman 3

Creation of the Taxman 3 architecture using Spring Integration in order to increase raw performance tenfold.

* Management of a team of 4 developers for the implementation of the architecture
* Implementation of end-to-end testing with Spring test and DB Unit

// end::project[]
// tag::project[]
==== Taxman 2

Design and implementation of the financial tax transaction on shares and derivatives for France and Italy. Worked on the backend with MQ, DB2 and Spring.

* Development of new features in the Taxman 2 tax calculation application
* Maintenance of a high profile/high volume system in Java
* Use of cutting-edge Java technologies such as JMS, CXF, Hibernate and Spring Framework
* Coordinate integration with customer documentation team

// end::project[]
// tag::project[]
=== Customer Tax Portal

Development and design of a Flex web portal. Changed the architecture to migrate the portal to ExtJS from Sencha and web sockets to pass data update notification to our users.

* Flex and Javascript development of the portal
* Integration of Swiss customers into the portal with added data access security

// end::project[]
// end::achievements[]

// tag::environment[]
Environment::
* Eclipse
* Git
* Java
* Spring
* Spring Integration
* Spring testing
* Mockito
* DBUnit
* Multithreading
* ExtJS
* MQ
* JMS
* DB2
* Jira
* Splunk
* Perl
* UML
* MS Project

// end::environment[]